// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.10
// source: pb/vote.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VoteRequestData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TermIndex uint64 `protobuf:"varint,1,opt,name=term_index,json=termIndex,proto3" json:"term_index,omitempty"` // 本机的任期号
	LogIndex  uint64 `protobuf:"varint,2,opt,name=log_index,json=logIndex,proto3" json:"log_index,omitempty"`    // 本机的最高日志编号
}

func (x *VoteRequestData) Reset() {
	*x = VoteRequestData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_vote_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VoteRequestData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteRequestData) ProtoMessage() {}

func (x *VoteRequestData) ProtoReflect() protoreflect.Message {
	mi := &file_pb_vote_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteRequestData.ProtoReflect.Descriptor instead.
func (*VoteRequestData) Descriptor() ([]byte, []int) {
	return file_pb_vote_proto_rawDescGZIP(), []int{0}
}

func (x *VoteRequestData) GetTermIndex() uint64 {
	if x != nil {
		return x.TermIndex
	}
	return 0
}

func (x *VoteRequestData) GetLogIndex() uint64 {
	if x != nil {
		return x.LogIndex
	}
	return 0
}

type VoteReplyData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Get uint32 `protobuf:"varint,1,opt,name=get,proto3" json:"get,omitempty"`
}

func (x *VoteReplyData) Reset() {
	*x = VoteReplyData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_vote_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VoteReplyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteReplyData) ProtoMessage() {}

func (x *VoteReplyData) ProtoReflect() protoreflect.Message {
	mi := &file_pb_vote_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteReplyData.ProtoReflect.Descriptor instead.
func (*VoteReplyData) Descriptor() ([]byte, []int) {
	return file_pb_vote_proto_rawDescGZIP(), []int{1}
}

func (x *VoteReplyData) GetGet() uint32 {
	if x != nil {
		return x.Get
	}
	return 0
}

type EntryClientInitDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SelfNode []*SelfNode `protobuf:"bytes,1,rep,name=selfNode,proto3" json:"selfNode,omitempty"` // 本机携带的节点
	SelfId   string      `protobuf:"bytes,2,opt,name=selfId,proto3" json:"selfId,omitempty"`
}

func (x *EntryClientInitDataRequest) Reset() {
	*x = EntryClientInitDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_vote_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntryClientInitDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryClientInitDataRequest) ProtoMessage() {}

func (x *EntryClientInitDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_vote_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryClientInitDataRequest.ProtoReflect.Descriptor instead.
func (*EntryClientInitDataRequest) Descriptor() ([]byte, []int) {
	return file_pb_vote_proto_rawDescGZIP(), []int{2}
}

func (x *EntryClientInitDataRequest) GetSelfNode() []*SelfNode {
	if x != nil {
		return x.SelfNode
	}
	return nil
}

func (x *EntryClientInitDataRequest) GetSelfId() string {
	if x != nil {
		return x.SelfId
	}
	return ""
}

type EntryClientInitDataReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SelfNode  []*SelfNode `protobuf:"bytes,1,rep,name=selfNode,proto3" json:"selfNode,omitempty"` // 本机携带的节点
	MasterId  string      `protobuf:"bytes,2,opt,name=masterId,proto3" json:"masterId,omitempty"`
	Increment bool        `protobuf:"varint,3,opt,name=increment,proto3" json:"increment,omitempty"` // 是否是增量节点
}

func (x *EntryClientInitDataReply) Reset() {
	*x = EntryClientInitDataReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_vote_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntryClientInitDataReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryClientInitDataReply) ProtoMessage() {}

func (x *EntryClientInitDataReply) ProtoReflect() protoreflect.Message {
	mi := &file_pb_vote_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryClientInitDataReply.ProtoReflect.Descriptor instead.
func (*EntryClientInitDataReply) Descriptor() ([]byte, []int) {
	return file_pb_vote_proto_rawDescGZIP(), []int{3}
}

func (x *EntryClientInitDataReply) GetSelfNode() []*SelfNode {
	if x != nil {
		return x.SelfNode
	}
	return nil
}

func (x *EntryClientInitDataReply) GetMasterId() string {
	if x != nil {
		return x.MasterId
	}
	return ""
}

func (x *EntryClientInitDataReply) GetIncrement() bool {
	if x != nil {
		return x.Increment
	}
	return false
}

type SelfNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TcpAddr string `protobuf:"bytes,2,opt,name=tcpAddr,proto3" json:"tcpAddr,omitempty"`
	RpcAddr string `protobuf:"bytes,3,opt,name=rpcAddr,proto3" json:"rpcAddr,omitempty"`
}

func (x *SelfNode) Reset() {
	*x = SelfNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_vote_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SelfNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelfNode) ProtoMessage() {}

func (x *SelfNode) ProtoReflect() protoreflect.Message {
	mi := &file_pb_vote_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelfNode.ProtoReflect.Descriptor instead.
func (*SelfNode) Descriptor() ([]byte, []int) {
	return file_pb_vote_proto_rawDescGZIP(), []int{4}
}

func (x *SelfNode) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SelfNode) GetTcpAddr() string {
	if x != nil {
		return x.TcpAddr
	}
	return ""
}

func (x *SelfNode) GetRpcAddr() string {
	if x != nil {
		return x.RpcAddr
	}
	return ""
}

var File_pb_vote_proto protoreflect.FileDescriptor

var file_pb_vote_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x70, 0x62, 0x2f, 0x76, 0x6f, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x02, 0x70, 0x62, 0x22, 0x4d, 0x0a, 0x0f, 0x56, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x69,
	0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x74, 0x65, 0x72, 0x6d,
	0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x6f, 0x67, 0x5f, 0x69, 0x6e, 0x64,
	0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x6c, 0x6f, 0x67, 0x49, 0x6e, 0x64,
	0x65, 0x78, 0x22, 0x21, 0x0a, 0x0d, 0x56, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x67, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x03, 0x67, 0x65, 0x74, 0x22, 0x5e, 0x0a, 0x1a, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x69, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x08, 0x73, 0x65, 0x6c, 0x66, 0x4e, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x6c, 0x66, 0x4e,
	0x6f, 0x64, 0x65, 0x52, 0x08, 0x73, 0x65, 0x6c, 0x66, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x65, 0x6c, 0x66, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x65, 0x6c, 0x66, 0x49, 0x64, 0x22, 0x7e, 0x0a, 0x18, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x69, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x28, 0x0a, 0x08, 0x73, 0x65, 0x6c, 0x66, 0x4e, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x6c, 0x66, 0x4e, 0x6f, 0x64,
	0x65, 0x52, 0x08, 0x73, 0x65, 0x6c, 0x66, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6d,
	0x61, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d,
	0x61, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6e, 0x63, 0x72, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x6e, 0x63, 0x72,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x4e, 0x0a, 0x08, 0x53, 0x65, 0x6c, 0x66, 0x4e, 0x6f, 0x64,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x63, 0x70, 0x41, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x74, 0x63, 0x70, 0x41, 0x64, 0x64, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x72,
	0x70, 0x63, 0x41, 0x64, 0x64, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x70,
	0x63, 0x41, 0x64, 0x64, 0x72, 0x32, 0x3f, 0x0a, 0x04, 0x56, 0x6f, 0x74, 0x65, 0x12, 0x37, 0x0a,
	0x0b, 0x56, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x13, 0x2e, 0x70,
	0x62, 0x2e, 0x56, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74,
	0x61, 0x1a, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x56, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x44, 0x61, 0x74, 0x61, 0x22, 0x00, 0x32, 0x55, 0x0a, 0x05, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x4c, 0x0a, 0x0a, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x69, 0x74, 0x12, 0x1e, 0x2e,
	0x70, 0x62, 0x2e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x6e,
	0x69, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e,
	0x70, 0x62, 0x2e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x6e,
	0x69, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x05, 0x5a,
	0x03, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_vote_proto_rawDescOnce sync.Once
	file_pb_vote_proto_rawDescData = file_pb_vote_proto_rawDesc
)

func file_pb_vote_proto_rawDescGZIP() []byte {
	file_pb_vote_proto_rawDescOnce.Do(func() {
		file_pb_vote_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_vote_proto_rawDescData)
	})
	return file_pb_vote_proto_rawDescData
}

var file_pb_vote_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pb_vote_proto_goTypes = []interface{}{
	(*VoteRequestData)(nil),            // 0: pb.VoteRequestData
	(*VoteReplyData)(nil),              // 1: pb.VoteReplyData
	(*EntryClientInitDataRequest)(nil), // 2: pb.EntryClientInitDataRequest
	(*EntryClientInitDataReply)(nil),   // 3: pb.EntryClientInitDataReply
	(*SelfNode)(nil),                   // 4: pb.SelfNode
}
var file_pb_vote_proto_depIdxs = []int32{
	4, // 0: pb.EntryClientInitDataRequest.selfNode:type_name -> pb.SelfNode
	4, // 1: pb.EntryClientInitDataReply.selfNode:type_name -> pb.SelfNode
	0, // 2: pb.Vote.VoteRequest:input_type -> pb.VoteRequestData
	2, // 3: pb.Entry.ClientInit:input_type -> pb.EntryClientInitDataRequest
	1, // 4: pb.Vote.VoteRequest:output_type -> pb.VoteReplyData
	3, // 5: pb.Entry.ClientInit:output_type -> pb.EntryClientInitDataReply
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pb_vote_proto_init() }
func file_pb_vote_proto_init() {
	if File_pb_vote_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_vote_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VoteRequestData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_vote_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VoteReplyData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_vote_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntryClientInitDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_vote_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntryClientInitDataReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_vote_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SelfNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_vote_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_pb_vote_proto_goTypes,
		DependencyIndexes: file_pb_vote_proto_depIdxs,
		MessageInfos:      file_pb_vote_proto_msgTypes,
	}.Build()
	File_pb_vote_proto = out.File
	file_pb_vote_proto_rawDesc = nil
	file_pb_vote_proto_goTypes = nil
	file_pb_vote_proto_depIdxs = nil
}
